title: "MedTranscribeAi Docs"
description: "Transcribe care. Optimize billing. Get paid faster."
#remote_theme: just-the-docs/just-the-docs
theme: jekyll-theme-cayman # or: jekyll-theme-primer, jekyll-theme-minimal, etc.
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# If this is a project site (not org/user site), set your baseurl:
#baseurl: "/medtranscribeai"

# Just the Docs options (optional, but handy)
logo: "/assets/iOSiconMedTranscribe.png"
aux_links:
  "MedTranscribeAi on GitHub":
    - "https://github.com/MedTranscribeAi"
nav_external_links_new_tab: true
